require "bundler/setup"
require "sequel"
require "yaml"
require "digest"

namespace :db do
  task :create do
    env = ENV['RACK_ENV'] || 'development'
    DB = Sequel.sqlite "#{env}.db"
    DB.create_table :attendees do
      primary_key :id
      column :name, String, :null => false
      column :organization, String, :null => false
      column :email, String, :null => false
      column :phone, String
    end
  end
end

namespace :users do
  task :create do
    password = 10.times.map { [*'0'..'9', *'a'..'z', *'A'..'Z'].sample }.join
    pass_digest = Digest::SHA256.hexdigest password

    File.open "users.yml", "w" do |f|
      f.write({ "meetup" => pass_digest }.to_yaml)
    end

    puts "generated password: #{password}"
  end
end
